airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy-account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy-user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy-password') }}"
      role: TRANSFORM
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev

elementary:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy-account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy-user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy-password') }}"
      role: TRANSFORM
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
