airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy-account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy-user') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY', 'dummy-key') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', 'dummy') }}"
      role: TRANSFORM
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH

elementary:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy-account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy-user') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY', 'dummy-key') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', 'dummy') }}"
      role: TRANSFORM
      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
